name: wanzo
description: "Une solution complète de gestion d'entreprise pour les PME africaines."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Commandes importantes:
# - flutter pub run build_runner build --delete-conflicting-outputs (Génère les adaptateurs Hive)

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI and design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  
  # State management
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  equatable: ^2.0.7
  
  # Navigation
  go_router: ^15.1.2
  
  # Storage and serialization
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1 # Added freezed_annotation
    
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  image_picker: ^1.1.0
  image_cropper: ^9.1.0 # Upgraded from ^6.0.0
  connectivity_plus: ^6.1.4 # Upgraded from ^5.0.2
  http: ^1.2.0
    # Authentication
  flutter_appauth: ^9.0.0
  flutter_secure_storage: ^9.2.0 # Upgraded from ^4.2.1
  jwt_decoder: ^2.0.1 # Pour décoder et analyser les JWT tokens
  
  # Display and rendering
  flutter_markdown: ^0.7.1
  flutter_math_fork: ^0.7.2
  flutter_syntax_view: ^4.0.0
  flutter_highlight: ^0.7.0
  
  # Input
  speech_to_text: ^7.0.0
    # Notifications
  flutter_local_notifications: ^19.2.0
  # firebase_core: ^2.24.2 # Commented out
  # firebase_messaging: ^14.7.10 # Commented out
  badges: ^3.1.2
  
  # PDF generation and printing
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^11.0.0
  fl_chart: ^1.0.0
  path: ^1.9.1
  flutter_gen: ^5.10.0
  cached_network_image: ^3.3.1 # Added for displaying network images
  flutter_cache_manager: ^3.4.1
  cloudinary_public: ^0.23.1
  flutter_dotenv: ^5.1.0 # Added flutter_dotenv
  photo_view: ^0.15.0 # Added photo_view for image zooming
  bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  freezed: ^2.5.2 # Added freezed
  mockito: ^5.4.5
  bloc_test: ^10.0.0 # Updated to be compatible with bloc ^9.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env # Added .env file

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# Configuration pour flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.jpg"
  web:
    generate: true
  windows:
    generate: true

# Configuration pour flutter_native_splash
flutter_native_splash:
  color: "#FFFFFF" # Couleur de fond blanche
  image: assets/images/logo-wanzo-orange-carre-500x500.png # Chemin vers votre image de splash
  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: center

  # Décommentez et personnalisez si vous avez une image spécifique pour Android 12+
  # android_12:
  #   image: assets/images/logo-wanzo-orange-carre-500x500.png 
  #   color: "#FFFFFF"
  #   icon_background_color: "#FFFFFF"
