name: wanzo
description: "Une solution complète de gestion d'entreprise pour les PME africaines."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Commandes importantes:
# - flutter pub run build_runner build --delete-conflicting-outputs (Génère les adaptateurs Hive)

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI and design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  
  # State management
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  equatable: ^2.0.7
  
  # Navigation
  go_router: ^15.1.2
  
  # Storage and serialization
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  sqflite: ^2.3.0
    
  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.2
  http: ^1.2.0
      # Authentication
  flutter_appauth: ^9.0.0
  flutter_secure_storage: ^8.0.0
  
  # Display and rendering
  flutter_markdown: ^0.7.1
  flutter_math_fork: ^0.7.2
  flutter_syntax_view: ^4.0.0
  flutter_highlight: ^0.7.0
  
  # Input
  speech_to_text: ^7.0.0
  
  # Notifications
  flutter_local_notifications: ^19.2.0
  # firebase_core: ^2.24.2 # Commented out
  # firebase_messaging: ^14.7.10 # Commented out
  badges: ^3.1.2
  
  # PDF generation and printing
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  json_serializable: ^6.7.1
  mockito: ^5.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# Configuration pour flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.jpg"
  web:
    generate: true
  windows:
    generate: true
