// Mocks generated by Mockito 5.4.5 from annotations
// in wanzo/test/features/adha/bloc/adha_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:wanzo/features/adha/models/adha_message.dart' as _i4;
import 'package:wanzo/features/adha/repositories/adha_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AdhaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdhaRepository extends _i1.Mock implements _i2.AdhaRepository {
  MockAdhaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.AdhaConversation>> getConversations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversations,
          [],
        ),
        returnValue: _i3.Future<List<_i4.AdhaConversation>>.value(
            <_i4.AdhaConversation>[]),
      ) as _i3.Future<List<_i4.AdhaConversation>>);

  @override
  _i3.Future<_i4.AdhaConversation?> getConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getConversation,
          [conversationId],
        ),
        returnValue: _i3.Future<_i4.AdhaConversation?>.value(),
      ) as _i3.Future<_i4.AdhaConversation?>);

  @override
  _i3.Future<void> saveConversation(_i4.AdhaConversation? conversation) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveConversation,
          [conversation],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteConversation,
          [conversationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> sendMessage({
    required String? conversationId,
    required String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {
            #conversationId: conversationId,
            #message: message,
          },
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #sendMessage,
            [],
            {
              #conversationId: conversationId,
              #message: message,
            },
          ),
        )),
      ) as _i3.Future<String>);
}
